#include <array>
#include <string>
#include <tuple>
#include <unordered_map>

enum class InstructionId
{
    ADD = 0,
    SUB,
    MUL,
    DIV,
    AND,
    OR,
    XOR,
    JZ,
    JNZ,
    MOV,
    LOAD,
    STOR,
    TSTB,
    SETZ,
    SETO,
    SET,
    PUSH,
    POP,
    NOT,
    SHFR,
    SHFL,
    INC,
    NOP,
    STOP,
    ADD_RM,
    ADD_MR,
    ADD_MM,
    SUB_RM,
    SUB_MR,
    SUB_MM,
    MUL_RM,
    MUL_MR,
    MUL_MM,
    DIV_RM,
    DIV_MR,
    DIV_MM,
    AND_RM,
    AND_MR,
    AND_MM,
    OR_RM,
    OR_MR,
    OR_MM,
    XOR_RM,
    XOR_MR,
    XOR_MM,
    JZ_RM,
    JZ_MR,
    JZ_MM,
    JNZ_RM,
    JNZ_MR,
    JNZ_MM,
    MOV_RM,
    MOV_MR,
    MOV_MM,
    TSTB_M,
    SETZ_M,
    SETO_M,
    SET_M,
    PUSH_M,
    POP_M,
    NOT_M,
    SHFR_M,
    SHFL_M,
    INC_M,
};

struct OpCode
{
    InstructionId name;
    uint16_t opCode;
    uint8_t argCount;
};

std::unordered_map<std::string, OpCode> opCodeTable = {

    {"ADD", OpCode{InstructionId::ADD, 0x0, 3}},         {"SUB", OpCode{InstructionId::SUB, 0x1, 3}},
    {"MUL", OpCode{InstructionId::MUL, 0x2, 3}},         {"DIV", OpCode{InstructionId::DIV, 0x3, 3}},
    {"AND", OpCode{InstructionId::AND, 0x4, 3}},         {"OR", OpCode{InstructionId::OR, 0x5, 3}},
    {"XOR", OpCode{InstructionId::XOR, 0x6, 3}},         {"JZ", OpCode{InstructionId::JZ, 0x70, 2}},
    {"JNZ", OpCode{InstructionId::JNZ, 0x71, 2}},        {"MOV", OpCode{InstructionId::MOV, 0x72, 2}},
    {"LOAD", OpCode{InstructionId::LOAD, 0x73, 2}},      {"STOR", OpCode{InstructionId::STOR, 0x74, 2}},
    {"TSTB", OpCode{InstructionId::TSTB, 0x75, 2}},      {"SETZ", OpCode{InstructionId::SETZ, 0x760, 1}},
    {"SETO", OpCode{InstructionId::SETO, 0x761, 1}},     {"SET", OpCode{InstructionId::SET, 0x762, 1}},
    {"PUSH", OpCode{InstructionId::PUSH, 0x763, 1}},     {"POP", OpCode{InstructionId::POP, 0x764, 1}},
    {"NOT", OpCode{InstructionId::NOT, 0x765, 1}},       {"SHFR", OpCode{InstructionId::SHFR, 0x766, 1}},
    {"SHFL", OpCode{InstructionId::SHFL, 0x767, 1}},     {"INC", OpCode{InstructionId::INC, 0x768, 1}},
    {"NOP", OpCode{InstructionId::NOP, 0x7690, 0}},      {"STOP", OpCode{InstructionId::STOP, 0x7691, 0}},
    {"ADD_RM", OpCode{InstructionId::ADD_RM, 0x77, 2}},  {"ADD_MR", OpCode{InstructionId::ADD_MR, 0x78, 2}},
    {"ADD_MM", OpCode{InstructionId::ADD_MM, 0x79, 2}},  {"SUB_RM", OpCode{InstructionId::SUB_RM, 0x7a, 2}},
    {"SUB_MR", OpCode{InstructionId::SUB_MR, 0x7b, 2}},  {"SUB_MM", OpCode{InstructionId::SUB_MM, 0x7c, 2}},
    {"MUL_RM", OpCode{InstructionId::MUL_RM, 0x7d, 2}},  {"MUL_MR", OpCode{InstructionId::MUL_MR, 0x7e, 2}},
    {"MUL_MM", OpCode{InstructionId::MUL_MM, 0x7f, 2}},  {"DIV_RM", OpCode{InstructionId::DIV_RM, 0x80, 2}},
    {"DIV_MR", OpCode{InstructionId::DIV_MR, 0x81, 2}},  {"DIV_MM", OpCode{InstructionId::DIV_MM, 0x82, 2}},
    {"AND_RM", OpCode{InstructionId::AND_RM, 0x83, 2}},  {"AND_MR", OpCode{InstructionId::AND_MR, 0x84, 2}},
    {"AND_MM", OpCode{InstructionId::AND_MM, 0x85, 2}},  {"OR_RM", OpCode{InstructionId::OR_RM, 0x86, 2}},
    {"OR_MR", OpCode{InstructionId::OR_MR, 0x87, 2}},    {"OR_MM", OpCode{InstructionId::OR_MM, 0x88, 2}},
    {"XOR_RM", OpCode{InstructionId::XOR_RM, 0x89, 2}},  {"XOR_MR", OpCode{InstructionId::XOR_MR, 0x8a, 2}},
    {"XOR_MM", OpCode{InstructionId::XOR_MM, 0x8b, 2}},  {"JZ_RM", OpCode{InstructionId::JZ_RM, 0x8c, 2}},
    {"JZ_MR", OpCode{InstructionId::JZ_MR, 0x8d, 2}},    {"JZ_MM", OpCode{InstructionId::JZ_MM, 0x8e, 2}},
    {"JNZ_RM", OpCode{InstructionId::JNZ_RM, 0x8f, 2}},  {"JNZ_MR", OpCode{InstructionId::JNZ_MR, 0x90, 2}},
    {"JNZ_MM", OpCode{InstructionId::JNZ_MM, 0x91, 2}},  {"MOV_RM", OpCode{InstructionId::MOV_RM, 0x92, 2}},
    {"MOV_MR", OpCode{InstructionId::MOV_MR, 0x93, 2}},  {"MOV_MM", OpCode{InstructionId::MOV_MM, 0x94, 2}},
    {"TSTB_M", OpCode{InstructionId::TSTB_M, 0x95, 2}},  {"SETZ_M", OpCode{InstructionId::SETZ_M, 0x76a, 1}},
    {"SETO_M", OpCode{InstructionId::SETO_M, 0x76b, 1}}, {"SET_M", OpCode{InstructionId::SET_M, 0x76c, 1}},
    {"PUSH_M", OpCode{InstructionId::PUSH_M, 0x76d, 1}}, {"POP_M", OpCode{InstructionId::POP_M, 0x76e, 1}},
    {"NOT_M", OpCode{InstructionId::NOT_M, 0x76f, 1}},   {"SHFR_M", OpCode{InstructionId::SHFR_M, 0x960, 1}},
    {"SHFL_M", OpCode{InstructionId::SHFL_M, 0x961, 1}}, {"INC_M", OpCode{InstructionId::INC_M, 0x962, 1}},
};
